name: Build and Deploy Docs

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

# Only allow one docs build at a time so that overlapping stale builds will get
# cancelled automatically.
concurrency:
  group: deploy_docs
  cancel-in-progress: true

jobs:
  build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Clone docs repo
        uses: actions/checkout@main
        with:
          path: docs      # place in a named directory

      - name: Clone main repo
        uses: actions/checkout@main
        with:
          path: napari
          ref: two-repo
          repository: melissawm/napari

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - uses: tlambert03/setup-qt-libs@v1

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install "napari/[all]"
          python -m pip install -r docs/requirements.txt

      - name: Testing
        run: |
          python -c 'import napari; print(napari.__version__)'
          python -c 'import napari.layers; print(napari.layers.__doc__)'

      - name: Build Docs
        uses: GabrielBB/xvfb-action@v1
        env:
          GOOGLE_CALENDAR_ID: ${{ secrets.GOOGLE_CALENDAR_ID }}
          GOOGLE_CALENDAR_API_KEY: ${{ secrets.GOOGLE_CALENDAR_API_KEY }}
        with:
          run: make -C docs/docs docs

      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          #deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          #external_repository: melissawm/napari.github.io
          publish_dir: docs/docs/_build
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          #cname: napari.org
